Repository googleapis/nodejs-common, pull requests merged in 2018-12, with the labels that each got.

#315 feat: add maybeOptionsOrCallback util method
  src/util.ts
  test/service.ts
  test/util.ts
Labels: cla: yes

#316 docs: update the badges on the readme
  README.md
Labels: cla: yes

#318 chore: update license file
  LICENSE
Labels: cla: yes

#321 chore: nyc ignore build/test by default
  .nycrc
Labels: cla: yes

#322 chore: always nyc report before calling codecov
  .kokoro/test.sh
Labels: cla: yes

#325 build: add Kokoro configs for autorelease
  .circleci/config.yml
  .circleci/npm-install-retry.js
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
Labels: cla: yes

#326 fix(build): fix Kokoro release script
  .kokoro/release/publish.cfg
Labels: cla: yes

#327 chore: fix publish.sh perm
  .kokoro/publish.sh
Labels: cla: yes

#329 chore: update nyc and eslint configs
  .eslintignore
  .nycrc
Labels: cla: yes

#330 chore(build): inject yoshi automation key
  .kokoro/release/publish.cfg
Labels: cla: yes

#331 fix: revert async behavior of request
  src/index.ts
  src/operation.ts
  src/service-object.ts
  src/service.ts
  system-test/fixtures/kitchen/src/index.ts
  test/service-object.ts
  test/service.ts
Labels: cla: yes, semver: major

#333 Release @google-cloud/common v0.28.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#335 fix: reverse order of request callback params
  src/index.ts
  src/service-object.ts
  src/service.ts
  src/util.ts
  test/service-object.ts
  test/service.ts
Labels: cla: yes

#338 fix: Revert "fix: reverse order of request callback params (#335)"
  src/index.ts
  src/service-object.ts
  src/service.ts
  src/util.ts
  test/service-object.ts
  test/service.ts
Labels: cla: yes

#337 fix: use request_ for service-object
  src/service-object.ts
  src/service.ts
  test/service-object.ts
Labels: cla: yes

#340 Release @google-cloud/common v0.29.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#341 fix: bind to this instead of true
  src/service.ts
Labels: cla: yes

#342 Release @google-cloud/common v0.29.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes
