Repository googleapis/nodejs-common, pull requests merged in 2019-07, with the labels that each got.

#451 fix: allow methodConfig to override request method and uri
  src/service-object.ts
  test/service-object.ts
Labels: cla: yes

#452 chore: release 2.0.4
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#450 fix(ts)!: provide optional typing for set/getMetadata
  src/service-object.ts
Labels: Breaking Change, cla: yes

#449 Includes the response in the error message when the response body can't be parsed as JSON.
  src/util.ts
  test/util.ts
Labels: cla: yes

#454 chore: release 2.0.5
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#457 docs: use the jsdoc-fresh theme
  .jsdoc.js
Labels: cla: yes

#455 feat: add timeout to options and use it in the reqOpts
  src/service.ts
  test/service.ts
Labels: cla: yes
