Repository googleapis/nodejs-common, pull requests merged in 2019-03, with the labels that each got.

#379 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#380 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#381 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#383 Release @google-cloud/common v0.31.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#384 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#385 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#388 fix(deps): bump the min version required for all deps
  package.json
Labels: automerge, cla: yes

#393 fix(ts): do not ship @types/duplexify
  package.json
  src/util.ts
  test/util.ts
Labels: cla: yes

#394 refactor: remove configurable request
  src/service-object.ts
  src/service.ts
  src/util.ts
  test/operation.ts
  test/service-object.ts
  test/util.ts
Labels: cla: yes
