Repository googleapis/nodejs-common, pull requests merged in 2019-04, with the labels that each got.

#397 fix: @types/node@11.13.0 breaks paginate/promisifyAll
  package.json
Labels: cla: yes

#400 Release @google-cloud/common v0.32.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes

#402 chore: unpin @types/node
  package.json
Labels: cla: yes

#403 fix: teeny-request should be dependency
  package.json
Labels: automerge, cla: yes

#405 Release @google-cloud/common v0.32.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#410 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes

#408 docs: use repo-metadata to generate the README
  .cloud-repo-tools.json
  .gitignore
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  package.json
  synth.metadata
Labels: cla: yes
