Repository googleapis/nodejs-common, pull requests merged in 2020-05, with the labels that each got.

#576 chore: unpin version of gts
  package.json
Labels: automerge, cla: yes

#578 fix: retry error code 408
  src/util.ts
  test/util.ts
Labels: cla: yes

#577 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#579 fix: allow users to set interceptors
  src/service-object.ts
  src/service.ts
Labels: cla: yes
