Repository googleapis/nodejs-common, pull requests merged in 2020-07, with the labels that each got.

#596 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#597 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#601 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#600 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#605 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#604 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#606 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#607 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#608 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#609 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#611 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#612 test: add basic system tests
  system-test/common.ts
Labels: cla: yes
