Repository googleapis/nodejs-common, pull requests merged in 2020-11, with the labels that each got.

#640 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
  test/util.ts
Labels: api: docs, cla: yes, context: full

#641 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, context: full

#634 feat: add ignoreNotFound to service-object#delete
  src/service-object.ts
  test/service-object.ts
Labels: cla: yes

#643 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
